import React from "react";
import { Box, Typography, Container, Link } from "@mui/material";

const PrivacyPolicy = () => {
  return (
    <Container maxWidth="md" sx={{ mt: 4, mb: 4 }}>
      <Box sx={{ my: 4 }}>
        <Typography variant="h4" component="h1" gutterBottom>
          Privacy Policy
        </Typography>
        <Typography variant="body1" paragraph>
          This Privacy Policy describes Our policies and procedures on the
          collection, use and disclosure of Your information when You use the
          Service and tells You about Your privacy rights and how the law
          protects You.
        </Typography>
        <Typography variant="h5" component="h2" gutterBottom>
          Interpretation and Definitions
        </Typography>
        <Typography variant="h6" component="h3" gutterBottom>
          Interpretation
        </Typography>
        <Typography variant="body1" paragraph>
          The words of which the initial letter is capitalized have meanings
          defined under the following conditions. The following definitions
          shall have the same meaning regardless of whether they appear in
          singular or in plural.
        </Typography>
        <Typography variant="h6" component="h3" gutterBottom>
          Definitions
        </Typography>
        <Typography variant="body1" paragraph>
          For the purposes of this Privacy Policy:
        </Typography>
        <ul>
          <li>
            <Typography variant="body1">
              <strong>Account</strong> means a unique account created for You to
              access our Service or parts of our Service.
            </Typography>
          </li>
          <li>
            <Typography variant="body1">
              <strong>Company</strong> (referred to as either "the Company",
              "We", "Us" or "Our" in this Agreement) refers to Your Website.
            </Typography>
          </li>
          <li>
            <Typography variant="body1">
              <strong>Cookies</strong> are small files that are placed on Your
              computer, mobile device or any other device by a website,
              containing the details of Your browsing history on that website
              among its many uses.
            </Typography>
          </li>
          <li>
            <Typography variant="body1">
              <strong>Country</strong> refers to: India
            </Typography>
          </li>
          <li>
            <Typography variant="body1">
              <strong>Device</strong> means any device that can access the
              Service such as a computer, a cellphone or a digital tablet.
            </Typography>
          </li>
          <li>
            <Typography variant="body1">
              <strong>Personal Data</strong> is any information that relates to
              an identified or identifiable individual.
            </Typography>
          </li>
          <li>
            <Typography variant="body1">
              <strong>Service</strong> refers to the Website.
            </Typography>
          </li>
          <li>
            <Typography variant="body1">
              <strong>Service Provider</strong> means any natural or legal
              person who processes the data on behalf of the Company. It refers
              to third-party companies or individuals employed by the Company to
              facilitate the Service, to provide the Service on behalf of the
              Company, to perform services related to the Service or to assist
              the Company in analyzing how the Service is used.
            </Typography>
          </li>
          <li>
            <Typography variant="body1">
              <strong>Usage Data</strong> refers to data collected
              automatically, either generated by the use of the Service or from
              the Service infrastructure itself (for example, the duration of a
              page visit).
            </Typography>
          </li>
          <li>
            <Typography variant="body1">
              <strong>Website</strong> refers to EMI Calculator, accessible from{" "}
              <Link href="https://yourwebsite.com/">https://yourwebsite.com/</Link>
            </Typography>
          </li>
          <li>
            <Typography variant="body1">
              <strong>You</strong> means the individual accessing or using the
              Service, or the company, or other legal entity on behalf of which
              such individual is accessing or using the Service, as applicable.
            </Typography>
          </li>
        </ul>

        <Typography variant="h5" component="h2" gutterBottom>
          Collecting and Using Your Personal Data
        </Typography>
        <Typography variant="h6" component="h3" gutterBottom>
          Types of Data Collected
        </Typography>
        <Typography variant="h6" component="h4" gutterBottom>
          Personal Data
        </Typography>
        <Typography variant="body1" paragraph>
          While using Our Service, We may ask You to provide Us with certain
          personally identifiable information that can be used to contact or
          identify You. Personally identifiable information may include, but is
          not limited to:
        </Typography>
        <ul>
          <li>
            <Typography variant="body1">Email address</Typography>
          </li>
          <li>
            <Typography variant="body1">First name and last name</Typography>
          </li>
          <li>
            <Typography variant="body1">Phone number</Typography>
          </li>
          <li>
            <Typography variant="body1">Address, State, Province, ZIP/Postal code, City</Typography>
          </li>
          <li>
            <Typography variant="body1">Usage Data</Typography>
          </li>
        </ul>

        <Typography variant="h6" component="h4" gutterBottom>
          Usage Data
        </Typography>
        <Typography variant="body1" paragraph>
          Usage Data is collected automatically when using the Service.
        </Typography>
        <Typography variant="body1" paragraph>
          Usage Data may include information such as Your Device's Internet
          Protocol address (e.g. IP address), browser type, browser version, the
          pages of our Service that You visit, the time and date of Your visit,
          the time spent on those pages, unique device identifiers and other
          diagnostic data.
        </Typography>
        <Typography variant="body1" paragraph>
          When You access the Service by or through a mobile device, We may
          collect certain information automatically, including, but not limited
          to, the type of mobile device You use, Your mobile device unique ID,
          the IP address of Your mobile device, Your mobile operating system,
          the type of mobile Internet browser You use, unique device identifiers
          and other diagnostic data.
        </Typography>
        <Typography variant="body1" paragraph>
          We may also collect information that Your browser sends whenever You
          visit our Service or when You access the Service by or through a
          mobile device.
        </Typography>

        <Typography variant="h6" component="h4" gutterBottom>
          Information from Third-Party Social Media Services
        </Typography>
        <Typography variant="body1" paragraph>
          The Company allows You to create an account and log in to use the
          Service through the following Third-party Social Media Services:
        </Typography>
        <ul>
          <li>
            <Typography variant="body1">Google</Typography>
          </li>
          <li>
            <Typography variant="body1">Facebook</Typography>
          </li>
          <li>
            <Typography variant="body1">Twitter</Typography>
          </li>
          <li>
            <Typography variant="body1">LinkedIn</Typography>
          </li>
        </ul>
        <Typography variant="body1" paragraph>
          If You decide to register through or otherwise grant us access to a
          Third-Party Social Media Service, We may collect Personal Data that is
          already associated with Your Third-Party Social Media Service's
          account, such as Your name, Your email address, Your activities or
          Your contact list associated with that account.
        </Typography>
        <Typography variant="body1" paragraph>
          You may also have the option to share additional information with the
          Company through Your Third-Party Social Media Service's account. If
          You choose to provide such information and Personal Data, You are
          giving the Company permission to use, share, and store it in a manner
          consistent with this Privacy Policy.
        </Typography>

        <Typography variant="h6" component="h4" gutterBottom>
          Tracking Technologies and Cookies
        </Typography>
        <Typography variant="body1" paragraph>
          We use Cookies and similar tracking technologies to track the activity
          on Our Service and store certain information. Tracking technologies
          used are beacons, tags, and scripts to collect and track information
          and to improve and analyze Our Service. The technologies We use may
          include:
        </Typography>
        <ul>
          <li>
            <Typography variant="body1">
              <strong>Cookies or Browser Cookies.</strong> A cookie is a small
              file placed on Your Device. You can instruct Your browser to
              refuse all Cookies or to indicate when a Cookie is being sent.
              However, if You do not accept Cookies, You may not be able to use
              some parts of our Service. Unless you have adjusted Your browser
              setting so that it will refuse Cookies, our Service may use
              Cookies.
            </Typography>
          </li>
          <li>
            <Typography variant="body1">
              <strong>Flash Cookies.</strong> Certain features of our Service
              may use local stored objects (or Flash Cookies) to collect and
              store information about Your preferences or Your activity on our
              Service. Flash Cookies are not managed by the same browser
              settings as those used for Browser Cookies. For more information
              on how You can delete Flash Cookies, please read "Where can I
              change the settings for disabling, or deleting local shared
              objects?" available at{" "}
              <Link href="https://helpx.adobe.com/flash-player/kb/disable-local-shared-objects-flash.html#main_Where_can_I_change_the_settings_for_disabling__or_deleting_local_shared_objects_">
                https://helpx.adobe.com/flash-player/kb/disable-local-shared-objects-flash.html#main_Where_can_I_change_the_settings_for_disabling__or_deleting_local_shared_objects_
              </Link>
            </Typography>
          </li>
          <li>
            <Typography variant="body1">
              <strong>Web Beacons.</strong> Certain sections of our Service and
              our emails may contain small electronic files known as web beacons
              (also referred to as clear gifs, pixel tags, and single-pixel
              gifs) that permit the Company, for example, to count users who
              have visited those pages or opened an email and for other related
              website statistics (for example, recording the popularity of a
              certain section and verifying system and server integrity).
            </Typography>
          </li>
        </ul>
        <Typography variant="body1" paragraph>
          Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies
          remain on Your personal computer or mobile device when You go offline,
          while Session Cookies are deleted as soon as You close Your web
          browser. Learn more about cookies on the Free Privacy Policy website
          article.
        </Typography>
        <Typography variant="body1" paragraph>
          We use both Session and Persistent Cookies for the purposes set out
          below:
        </Typography>
        <ul>
          <li>
            <Typography variant="body1">
              <strong>Necessary / Essential Cookies</strong>
              <br />
              Type: Session Cookies
              <br />
              Administered by: Us
              <br />
              Purpose: These Cookies are essential to provide You with services
              available through the Website and to enable You to use some of its
              features. They help to authenticate users and prevent fraudulent
              use of user accounts. Without these Cookies, the services that You
              have asked for cannot be provided, and We only use these Cookies
              to provide You with those services.
            </Typography>
          </li>
          <li>
            <Typography variant="body1">
              <strong>Cookies Policy / Notice Acceptance Cookies</strong>
              <br />
              Type: Persistent Cookies
              <br />
              Administered by: Us
              <br />
              Purpose: These Cookies identify if users have accepted the use of
              cookies on the Website.
            </Typography>
          </li>
          <li>
            <Typography variant="body1">
              <strong>Functionality Cookies</strong>
              <br />
              Type: Persistent Cookies
              <br />
              Administered by: Us
              <br />
              Purpose: These Cookies allow us to remember choices You make when
              You use the Website, such as remembering your login details or
              language preference. The purpose of these Cookies is to provide
              You with a more personal experience and to avoid You having to
              re-enter your preferences every time You use the Website.
            </Typography>
          </li>
        </ul>

        <Typography variant="h5" component="h2" gutterBottom>
          Use of Your Personal Data
        </Typography>
        <Typography variant="body1" paragraph>
          The Company may use Personal Data for the following purposes:
        </Typography>
        <ul>
          <li>
            <Typography variant="body1">
              <strong>To provide and maintain our Service</strong>, including to
              monitor the usage of our Service.
            </Typography>
          </li>
          <li>
            <Typography variant="body1">
              <strong>To manage Your Account:</strong> to manage Your
              registration as a user of the Service. The Personal Data You
              provide can give You access to different functionalities of the
              Service that are available to You as a registered user.
            </Typography>
          </li>
          <li>
            <Typography variant="body1">
              <strong>For the performance of a contract:</strong> the
              development, compliance and undertaking of the purchase contract
              for the products, items or services You have purchased or of any
              other contract with Us through the Service.
            </Typography>
          </li>
          <li>
            <Typography variant="body1">
              <strong>To contact You:</strong> To contact You by email,
              telephone calls, SMS, or other equivalent forms of electronic
              communication, such as a mobile application's push notifications
              regarding updates or informative communications related to the
              functionalities, products or contracted services, including the
              security updates, when necessary or reasonable for their
              implementation.
            </Typography>
          </li>
          <li>
            <Typography variant="body1">
              <strong>To provide You</strong> with news, special offers and
              general information about other goods, services and events which
              we offer that are similar to those that you have already purchased
              or enquired about unless You have opted not to receive such
              information.
            </Typography>
          </li>
          <li>
            <Typography variant="body1">
              <strong>To manage Your requests:</strong> To attend and manage
              Your requests to Us.
            </Typography>
          </li>
          <li>
            <Typography variant="body1">
              <strong>For business transfers:</strong> We may use Your
              information to evaluate or conduct a merger, divestiture,
              restructuring, reorganization, dissolution, or other sale or
              transfer of some or all of Our assets, whether as a going concern
              or as part of bankruptcy, liquidation, or similar proceeding, in
              which Personal Data held by Us about our Service users is among
              the assets transferred.
            </Typography>
          </li>
          <li>
            <Typography variant="body1">
              <strong>For other purposes</strong>: We may use Your information
              for other purposes, such as data analysis, identifying usage
              trends, determining the effectiveness of our promotional campaigns
              and to evaluate and improve our Service, products, services,
              marketing and your experience.
            </Typography>
          </li>
        </ul>

        <Typography variant="h5" component="h2" gutterBottom>
          Disclosure of Your Personal Data
        </Typography>
        <Typography variant="h6" component="h3" gutterBottom>
          Business Transactions
        </Typography>
        <Typography variant="body1" paragraph>
          If the Company is involved in a merger, acquisition or asset sale, Your
          Personal Data may be transferred. We will provide notice before Your
          Personal Data is transferred and becomes subject to a different
          Privacy Policy.
        </Typography>
        <Typography variant="h6" component="h3" gutterBottom>
          Law enforcement
        </Typography>
        <Typography variant="body1" paragraph>
          Under certain circumstances, the Company may be required to disclose
          Your Personal Data if required to do so by law or in response to valid
          requests by public authorities (e.g. a court or a government agency).
        </Typography>
        <Typography variant="h6" component="h3" gutterBottom>
          Other legal requirements
        </Typography>
        <Typography variant="body1" paragraph>
          The Company may disclose Your Personal Data in the good faith belief
          that such action is necessary to:
        </Typography>
        <ul>
          <li>
            <Typography variant="body1">Comply with a legal obligation</Typography>
          </li>
          <li>
            <Typography variant="body1">Protect and defend the rights or property of the Company</Typography>
          </li>
          <li>
            <Typography variant="body1">Prevent or investigate possible wrongdoing in connection with the Service</Typography>
          </li>
          <li>
            <Typography variant="body1">Protect the personal safety of Users of the Service or the public</Typography>
          </li>
          <li>
            <Typography variant="body1">Protect against legal liability</Typography>
          </li>
        </ul>

        <Typography variant="h5" component="h2" gutterBottom>
          Security of Your Personal Data
        </Typography>
        <Typography variant="body1" paragraph>
          The security of Your Personal Data is important to Us, but remember
          that no method of transmission over the Internet, or method of
          electronic storage is 100% secure. While We strive to use commercially
          acceptable means to protect Your Personal Data, We cannot guarantee
          its absolute security.
        </Typography>

        <Typography variant="h5" component="h2" gutterBottom>
          Children's Privacy
        </Typography>
        <Typography variant="body1" paragraph>
          Our Service does not address anyone under the age of 13. We do not
          knowingly collect personally identifiable information from anyone
          under the age of 13. If You are a parent or guardian and You are aware
          that Your child has provided Us with Personal Data, please contact Us.
          If We become aware that We have collected Personal Data from anyone
          under the age of 13 without verification of parental consent, We take
          steps to remove that information from Our servers.
        </Typography>
        <Typography variant="body1" paragraph>
          If We need to rely on consent as a legal basis for processing Your
          information and Your country requires consent from a parent, We may
          require Your parent's consent before We collect and use that
          information.
        </Typography>

        <Typography variant="h5" component="h2" gutterBottom>
          Links to Other Websites
        </Typography>
        <Typography variant="body1" paragraph>
          Our Service may contain links to other websites that are not operated
          by Us. If You click on a third party link, You will be directed to
          that third party's site. We strongly advise You to review the Privacy
          Policy of every site You visit.
        </Typography>
        <Typography variant="body1" paragraph>
          We have no control over and assume no responsibility for the content,
          privacy policies or practices of any third party sites or services.
        </Typography>

        <Typography variant="h5" component="h2" gutterBottom>
          Changes to this Privacy Policy
        </Typography>
        <Typography variant="body1" paragraph>
          We may update Our Privacy Policy from time to time. We will notify You
          of any changes by posting the new Privacy Policy on this page.
        </Typography>
        <Typography variant="body1" paragraph>
          We will let You know via email and/or a prominent notice on Our
          Service, prior to the change becoming effective and update the "Last
          updated" date at the top of this Privacy Policy.
        </Typography>
        <Typography variant="body1" paragraph>
          You are advised to review this Privacy Policy periodically for any
          changes. Changes to this Privacy Policy are effective when they are
          posted on this page.
        </Typography>

        <Typography variant="h5" component="h2" gutterBottom>
          Contact Us
        </Typography>
        <Typography variant="body1" paragraph>
          If you have any questions about this Privacy Policy, You can contact
          us:
        </Typography>
        <ul>
          <li>
            <Typography variant="body1">By email: support@yourwebsite.com</Typography>
          </li>
          <li>
            <Typography variant="body1">By visiting this page on our website: <Link href="https://yourwebsite.com/contact">https://yourwebsite.com/contact</Link></Typography>
          </li>
        </ul>
      </Box>
    </Container>
  );
};

export default PrivacyPolicy;
